version: '3.1'

networks:
  nginx-acme:
    driver: bridge
  rfproxy:
    external: true
  cf-tunnel:
    external: true

services:
  nginx:
    image: nginx:stable-alpine3.19-slim
    container_name: nginx
    restart: always
    ports:
      - 443:443
      - 8338:8338
      # - 127.0.0.1:8338:8338
    # expose:
    #   - "8338"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - nginx-acme
      - rfproxy 
      - cf-tunnel

  acme:
    image: neilpang/acme.sh:3.1.1
    container_name: acme-sh
    env_file:
      - .env
    environment:
      - CF_TOKEN=${CF_API_TOKEN}
      - CF_DOMAIN=${CF_DOMAIN}
      - CF_WC_DOMAIN=${CF_WC_DOMAIN}
    volumes:
      - ./certs:/acme.sh
      - ./acme/issue-cert.sh:/issue-cert.sh
    entrypoint: ["sh", "/issue-cert.sh"]
    networks:
      - nginx-acme
